// Seed data for Northstar Digital Services — fictional IT services vendor

export type Tier = "Tier 1" | "Tier 2" | "Tier 3";
export type Stance =
  | "Friendly"
  | "Neutral"
  | "Inattentive"
  | "Irrelevant"
  | "Combative"
  | "Unknown";
export type Rating = "A+" | "A" | "B+" | "B";
export type ReadinessBand =
  | "Strong"
  | "Adequate"
  | "Weak"
  | "Missing"
  | "Unsupported";

export const ANALYST_HOUSES = [
  { id: "gartner", name: "Gartner", tier: "Tier 1", model: "Magic Quadrant" },
  { id: "forrester", name: "Forrester", tier: "Tier 1", model: "Wave" },
  { id: "idc", name: "IDC", tier: "Tier 1", model: "MarketScape" },
  { id: "everest", name: "Everest Group", tier: "Tier 2", model: "PEAK Matrix" },
  { id: "hfs", name: "HFS Research", tier: "Tier 2", model: "Horizons" },
  { id: "nelsonhall", name: "NelsonHall", tier: "Tier 2", model: "NEAT" },
  { id: "isg", name: "ISG", tier: "Tier 2", model: "Provider Lens" },
] as const;

export type Analyst = {
  id: string;
  name: string;
  initials: string;
  house: string;
  houseTier: Tier;
  role: string;
  rating: Rating;
  confidence: number; // 0..1
  stance: Stance;
  stanceConfidence: number;
  coverage: string[];
  lastInteraction: string;
  source: "External import" | "Public discovery" | "Customer sync" | "User added";
  override?: boolean;
};

export const ANALYSTS: Analyst[] = [
  // ── GARTNER (Tier 1) ──────────────────────────────────────────────────
  {
    id: "g1",
    name: "Cathy Tornbohm",
    initials: "CT",
    house: "Gartner",
    houseTier: "Tier 1",
    role: "VP Analyst, BPO & Intelligent Automation",
    rating: "A+",
    confidence: 0.94,
    stance: "Unknown",
    stanceConfidence: 0.40,
    coverage: ["BPO", "Intelligent Automation", "RPA", "Finance & Accounting BPO"],
    lastInteraction: "Never",
    source: "Public discovery",
  },
  {
    id: "g2",
    name: "Jim Longwood",
    initials: "JL",
    house: "Gartner",
    houseTier: "Tier 1",
    role: "VP Distinguished Analyst, IT Sourcing & Outsourcing",
    rating: "A+",
    confidence: 0.91,
    stance: "Unknown",
    stanceConfidence: 0.38,
    coverage: ["IT Outsourcing", "Sourcing Advisory", "Managed Services", "Vendor Management"],
    lastInteraction: "Never",
    source: "Public discovery",
  },
  {
    id: "g3",
    name: "Helen Huntley",
    initials: "HH",
    house: "Gartner",
    houseTier: "Tier 1",
    role: "VP Analyst, IT Sourcing & Strategic Ecosystems",
    rating: "A+",
    confidence: 0.90,
    stance: "Unknown",
    stanceConfidence: 0.38,
    coverage: ["IT Sourcing", "Outsourcing Strategy", "Vendor Management", "ITO"],
    lastInteraction: "Never",
    source: "Public discovery",
  },
  {
    id: "g4",
    name: "Rajesh Kandaswamy",
    initials: "RK",
    house: "Gartner",
    houseTier: "Tier 1",
    role: "VP Analyst, Generative AI & AI Applications",
    rating: "A+",
    confidence: 0.89,
    stance: "Unknown",
    stanceConfidence: 0.38,
    coverage: ["Generative AI", "AI Applications", "AI Services", "Enterprise AI"],
    lastInteraction: "Never",
    source: "Public discovery",
  },
  {
    id: "g5",
    name: "Arup Roy",
    initials: "AR",
    house: "Gartner",
    houseTier: "Tier 1",
    role: "VP Analyst, AI Platforms & Data Science",
    rating: "A",
    confidence: 0.86,
    stance: "Unknown",
    stanceConfidence: 0.37,
    coverage: ["AI Platforms", "Machine Learning", "Data Science", "MLOps"],
    lastInteraction: "Never",
    source: "Public discovery",
  },
  {
    id: "g6",
    name: "Bryan Britz",
    initials: "BB",
    house: "Gartner",
    houseTier: "Tier 1",
    role: "Sr Director Analyst, Digital Workplace Services",
    rating: "A",
    confidence: 0.81,
    stance: "Unknown",
    stanceConfidence: 0.35,
    coverage: ["Digital Workplace", "End User Services", "Managed Desktop", "Employee Experience"],
    lastInteraction: "Never",
    source: "Public discovery",
  },
  {
    id: "g7",
    name: "Frank Ridder",
    initials: "FR",
    house: "Gartner",
    houseTier: "Tier 1",
    role: "VP Analyst, Digital Business & Innovation Services",
    rating: "A",
    confidence: 0.83,
    stance: "Unknown",
    stanceConfidence: 0.36,
    coverage: ["Digital Transformation Services", "Innovation Services", "IT Services EMEA"],
    lastInteraction: "Never",
    source: "Public discovery",
  },
  {
    id: "g8",
    name: "Deborah Wilson",
    initials: "DW",
    house: "Gartner",
    houseTier: "Tier 1",
    role: "Managing VP, Technology & Service Provider Research",
    rating: "A+",
    confidence: 0.90,
    stance: "Unknown",
    stanceConfidence: 0.38,
    coverage: ["IT Services", "Outsourcing", "Managed Services", "Cloud Services"],
    lastInteraction: "Never",
    source: "Public discovery",
  },
  {
    id: "g9",
    name: "Will Hahn",
    initials: "WH",
    house: "Gartner",
    houseTier: "Tier 1",
    role: "Principal Analyst, IT Services Sourcing",
    rating: "A",
    confidence: 0.79,
    stance: "Unknown",
    stanceConfidence: 0.35,
    coverage: ["IT Outsourcing", "Application Services", "Sourcing Advisory"],
    lastInteraction: "Never",
    source: "Public discovery",
  },
  {
    id: "g10",
    name: "Sid Nag",
    initials: "SN",
    house: "Gartner",
    houseTier: "Tier 1",
    role: "VP Analyst, Cloud Strategy & Infrastructure Services",
    rating: "A",
    confidence: 0.84,
    stance: "Unknown",
    stanceConfidence: 0.37,
    coverage: ["Cloud Services", "Cloud ITO", "Hyperscaler Ecosystems", "Cloud Migration"],
    lastInteraction: "Never",
    source: "Public discovery",
  },

  // ── FORRESTER (Tier 1) ────────────────────────────────────────────────
  {
    id: "f1",
    name: "J.P. Gownder",
    initials: "JG",
    house: "Forrester",
    houseTier: "Tier 1",
    role: "VP Principal Analyst, AI & Automation",
    rating: "A+",
    confidence: 0.90,
    stance: "Unknown",
    stanceConfidence: 0.40,
    coverage: ["AI Strategy", "Automation", "Future of Work", "Workforce Transformation"],
    lastInteraction: "Never",
    source: "Public discovery",
  },
  {
    id: "f2",
    name: "Craig LeClair",
    initials: "CL",
    house: "Forrester",
    houseTier: "Tier 1",
    role: "VP Principal Analyst, Intelligent Automation",
    rating: "A+",
    confidence: 0.92,
    stance: "Unknown",
    stanceConfidence: 0.40,
    coverage: ["RPA", "Intelligent Automation", "Process Mining", "Hyperautomation"],
    lastInteraction: "Never",
    source: "Public discovery",
  },
  {
    id: "f3",
    name: "Leslie Joseph",
    initials: "LJ",
    house: "Forrester",
    houseTier: "Tier 1",
    role: "Principal Analyst, AI & Decision Intelligence",
    rating: "A",
    confidence: 0.84,
    stance: "Unknown",
    stanceConfidence: 0.37,
    coverage: ["AI Strategy", "Decision Intelligence", "AI Ethics", "Enterprise AI"],
    lastInteraction: "Never",
    source: "Public discovery",
  },
  {
    id: "f4",
    name: "Glenn O'Donnell",
    initials: "GO",
    house: "Forrester",
    houseTier: "Tier 1",
    role: "VP Research Director, IT Operations & Automation",
    rating: "A",
    confidence: 0.83,
    stance: "Unknown",
    stanceConfidence: 0.37,
    coverage: ["IT Operations", "AIOps", "Site Reliability", "Managed Operations"],
    lastInteraction: "Never",
    source: "Public discovery",
  },
  {
    id: "f5",
    name: "Rowan Curran",
    initials: "RC",
    house: "Forrester",
    houseTier: "Tier 1",
    role: "Principal Analyst, AI & Emerging Technologies",
    rating: "A",
    confidence: 0.81,
    stance: "Unknown",
    stanceConfidence: 0.36,
    coverage: ["Generative AI", "Foundation Models", "AI Engineering", "AI Services"],
    lastInteraction: "Never",
    source: "Public discovery",
  },
  {
    id: "f6",
    name: "Martha Bennett",
    initials: "MB",
    house: "Forrester",
    houseTier: "Tier 1",
    role: "VP Principal Analyst, Data & AI",
    rating: "A",
    confidence: 0.82,
    stance: "Unknown",
    stanceConfidence: 0.37,
    coverage: ["Data Strategy", "AI Platforms", "Enterprise Data", "Data Governance"],
    lastInteraction: "Never",
    source: "Public discovery",
  },
  {
    id: "f7",
    name: "Kate Leggett",
    initials: "KL",
    house: "Forrester",
    houseTier: "Tier 1",
    role: "VP Principal Analyst, CRM & Customer Service",
    rating: "B+",
    confidence: 0.76,
    stance: "Unknown",
    stanceConfidence: 0.34,
    coverage: ["Customer Service", "CRM", "Contact Center", "Customer Experience BPO"],
    lastInteraction: "Never",
    source: "Public discovery",
  },
  {
    id: "f8",
    name: "Stephanie Balaouras",
    initials: "SB",
    house: "Forrester",
    houseTier: "Tier 1",
    role: "VP Research Director, Security & Risk",
    rating: "A",
    confidence: 0.85,
    stance: "Unknown",
    stanceConfidence: 0.37,
    coverage: ["Cybersecurity Services", "Managed Security", "Zero Trust", "Security Operations"],
    lastInteraction: "Never",
    source: "Public discovery",
  },
  {
    id: "f9",
    name: "Jeff Pollard",
    initials: "JP",
    house: "Forrester",
    houseTier: "Tier 1",
    role: "VP Principal Analyst, Security & Risk",
    rating: "A",
    confidence: 0.83,
    stance: "Unknown",
    stanceConfidence: 0.36,
    coverage: ["Cybersecurity", "SOC-as-a-Service", "Security Strategy", "CISO Advisory"],
    lastInteraction: "Never",
    source: "Public discovery",
  },

  // ── IDC (Tier 1) ──────────────────────────────────────────────────────
  {
    id: "i1",
    name: "Gard Little",
    initials: "GL",
    house: "IDC",
    houseTier: "Tier 1",
    role: "Group VP, IT Services Research",
    rating: "A+",
    confidence: 0.89,
    stance: "Unknown",
    stanceConfidence: 0.38,
    coverage: ["IT Services", "ITO", "Managed Services", "Global IT Services Market"],
    lastInteraction: "Never",
    source: "Public discovery",
  },
  {
    id: "i2",
    name: "Jennifer Hamel",
    initials: "JH",
    house: "IDC",
    houseTier: "Tier 1",
    role: "Research Director, Business Process Services",
    rating: "A",
    confidence: 0.83,
    stance: "Unknown",
    stanceConfidence: 0.36,
    coverage: ["BPO", "Business Process Services", "Finance & Accounting BPO", "HR BPO"],
    lastInteraction: "Never",
    source: "Public discovery",
  },
  {
    id: "i3",
    name: "Deepika Giri",
    initials: "DG",
    house: "IDC",
    houseTier: "Tier 1",
    role: "Research VP, Digital Business Services",
    rating: "A",
    confidence: 0.82,
    stance: "Unknown",
    stanceConfidence: 0.36,
    coverage: ["Digital Transformation Services", "AI Services", "Data & Analytics Services"],
    lastInteraction: "Never",
    source: "Public discovery",
  },
  {
    id: "i4",
    name: "Phil Sargeant",
    initials: "PS",
    house: "IDC",
    houseTier: "Tier 1",
    role: "Research Director, Cloud & IT Infrastructure Services",
    rating: "A",
    confidence: 0.80,
    stance: "Unknown",
    stanceConfidence: 0.36,
    coverage: ["Cloud ITO", "Infrastructure Services", "Managed Cloud", "Cloud Migration"],
    lastInteraction: "Never",
    source: "Public discovery",
  },
  {
    id: "i5",
    name: "Frank Dickson",
    initials: "FD",
    house: "IDC",
    houseTier: "Tier 1",
    role: "Group VP, Cybersecurity Products & Services",
    rating: "A",
    confidence: 0.81,
    stance: "Unknown",
    stanceConfidence: 0.36,
    coverage: ["Cybersecurity Services", "Managed Security", "Threat Intelligence", "SOC"],
    lastInteraction: "Never",
    source: "Public discovery",
  },
  {
    id: "i6",
    name: "Margaret Adam",
    initials: "MA",
    house: "IDC",
    houseTier: "Tier 1",
    role: "Research Director, Digital Business Services",
    rating: "B+",
    confidence: 0.77,
    stance: "Unknown",
    stanceConfidence: 0.34,
    coverage: ["Digital Services", "IT Services Sourcing", "Outsourcing", "Digital Transformation"],
    lastInteraction: "Never",
    source: "Public discovery",
  },
  {
    id: "i7",
    name: "Robert Young",
    initials: "RY",
    house: "IDC",
    houseTier: "Tier 1",
    role: "Group VP, Cloud Computing & Infrastructure",
    rating: "B+",
    confidence: 0.76,
    stance: "Unknown",
    stanceConfidence: 0.34,
    coverage: ["Cloud Computing", "Cloud IaaS", "Cloud Managed Services", "Hybrid Infrastructure"],
    lastInteraction: "Never",
    source: "Public discovery",
  },

  // ── EVEREST GROUP (Tier 2) ────────────────────────────────────────────
  {
    id: "e1",
    name: "Yugal Joshi",
    initials: "YJ",
    house: "Everest Group",
    houseTier: "Tier 2",
    role: "Partner & VP, Cloud & Digital Services",
    rating: "A+",
    confidence: 0.91,
    stance: "Unknown",
    stanceConfidence: 0.40,
    coverage: ["Cloud Services", "Digital Transformation", "Application Services", "PEAK Matrix"],
    lastInteraction: "Never",
    source: "Public discovery",
  },
  {
    id: "e2",
    name: "Salil Dani",
    initials: "SD",
    house: "Everest Group",
    houseTier: "Tier 2",
    role: "Partner, AI & Analytics Services",
    rating: "A+",
    confidence: 0.89,
    stance: "Unknown",
    stanceConfidence: 0.40,
    coverage: ["AI Services", "Analytics & BI", "Data Engineering", "Generative AI Services"],
    lastInteraction: "Never",
    source: "Public discovery",
  },
  {
    id: "e3",
    name: "Ronak Doshi",
    initials: "RD",
    house: "Everest Group",
    houseTier: "Tier 2",
    role: "Partner, Cloud & Infrastructure Services",
    rating: "A",
    confidence: 0.87,
    stance: "Unknown",
    stanceConfidence: 0.38,
    coverage: ["Cloud Infrastructure", "Managed Cloud", "Hybrid Cloud", "IaaS & PaaS Services"],
    lastInteraction: "Never",
    source: "Public discovery",
  },
  {
    id: "e4",
    name: "Akhilesh Tumar",
    initials: "AT",
    house: "Everest Group",
    houseTier: "Tier 2",
    role: "Practice Director, BFSI IT Services",
    rating: "A",
    confidence: 0.84,
    stance: "Unknown",
    stanceConfidence: 0.37,
    coverage: ["BFSI IT Services", "Banking Technology", "Insurance IT", "Capital Markets IT"],
    lastInteraction: "Never",
    source: "Public discovery",
  },
  {
    id: "e5",
    name: "Reetika Fleming",
    initials: "RF",
    house: "Everest Group",
    houseTier: "Tier 2",
    role: "VP Research, Banking & Financial Services",
    rating: "A",
    confidence: 0.85,
    stance: "Unknown",
    stanceConfidence: 0.38,
    coverage: ["BFSI BPO", "Mortgage BPS", "Capital Markets Operations", "Banking Process Services"],
    lastInteraction: "Never",
    source: "Public discovery",
  },
  {
    id: "e6",
    name: "Manu Aggarwal",
    initials: "MA",
    house: "Everest Group",
    houseTier: "Tier 2",
    role: "VP Research, Business Process Services",
    rating: "A",
    confidence: 0.83,
    stance: "Unknown",
    stanceConfidence: 0.37,
    coverage: ["BPO", "Finance & Accounting BPO", "Procurement BPO", "Shared Services"],
    lastInteraction: "Never",
    source: "Public discovery",
  },
  {
    id: "e7",
    name: "Chirajeet Sengupta",
    initials: "CS",
    house: "Everest Group",
    houseTier: "Tier 2",
    role: "Partner, Application & Digital Services",
    rating: "A",
    confidence: 0.85,
    stance: "Unknown",
    stanceConfidence: 0.38,
    coverage: ["Application Modernisation", "Digital Transformation", "ADM Services", "Product Engineering"],
    lastInteraction: "Never",
    source: "Public discovery",
  },
  {
    id: "e8",
    name: "Abhishek Singh",
    initials: "AS",
    house: "Everest Group",
    houseTier: "Tier 2",
    role: "Practice Director, Intelligent Automation",
    rating: "A",
    confidence: 0.82,
    stance: "Unknown",
    stanceConfidence: 0.36,
    coverage: ["Intelligent Automation", "RPA", "Hyperautomation", "Process Mining"],
    lastInteraction: "Never",
    source: "Public discovery",
  },
  {
    id: "e9",
    name: "Alisha Mittal",
    initials: "AM",
    house: "Everest Group",
    houseTier: "Tier 2",
    role: "Practice Director, Cybersecurity Services",
    rating: "A",
    confidence: 0.82,
    stance: "Unknown",
    stanceConfidence: 0.36,
    coverage: ["Managed Security Services", "Cybersecurity PEAK Matrix", "SOC Operations", "Threat Management"],
    lastInteraction: "Never",
    source: "Public discovery",
  },
  {
    id: "e10",
    name: "Sandy Notaro",
    initials: "SN",
    house: "Everest Group",
    houseTier: "Tier 2",
    role: "Partner, Healthcare & Life Sciences BPS",
    rating: "B+",
    confidence: 0.76,
    stance: "Unknown",
    stanceConfidence: 0.34,
    coverage: ["Healthcare IT Services", "Life Sciences BPO", "Payer Administration", "Provider IT"],
    lastInteraction: "Never",
    source: "Public discovery",
  },

  // ── HFS RESEARCH (Tier 2) ─────────────────────────────────────────────
  {
    id: "h1",
    name: "Phil Fersht",
    initials: "PF",
    house: "HFS Research",
    houseTier: "Tier 2",
    role: "CEO & Chief Analyst",
    rating: "A+",
    confidence: 0.94,
    stance: "Unknown",
    stanceConfidence: 0.40,
    coverage: ["BPO", "Outsourcing Strategy", "AI & Automation", "OneEcosystem", "Future of Work"],
    lastInteraction: "Never",
    source: "Public discovery",
  },
  {
    id: "h2",
    name: "Tom Reuner",
    initials: "TR",
    house: "HFS Research",
    houseTier: "Tier 2",
    role: "SVP Research, Intelligent Automation",
    rating: "A+",
    confidence: 0.91,
    stance: "Unknown",
    stanceConfidence: 0.40,
    coverage: ["Intelligent Automation", "RPA", "AI-led Automation", "Hyperautomation"],
    lastInteraction: "Never",
    source: "Public discovery",
  },
  {
    id: "h3",
    name: "Melissa O'Brien",
    initials: "MO",
    house: "HFS Research",
    houseTier: "Tier 2",
    role: "Research VP, Intelligent Operations",
    rating: "A",
    confidence: 0.86,
    stance: "Unknown",
    stanceConfidence: 0.38,
    coverage: ["BPO", "Intelligent Operations", "Digital Transformation", "Shared Services"],
    lastInteraction: "Never",
    source: "Public discovery",
  },
  {
    id: "h4",
    name: "Charles Sutherland",
    initials: "CS",
    house: "HFS Research",
    houseTier: "Tier 2",
    role: "Chief Research Officer",
    rating: "A",
    confidence: 0.84,
    stance: "Unknown",
    stanceConfidence: 0.37,
    coverage: ["IT Services", "OneOffice", "Business & Technology Services", "Digital Enterprise"],
    lastInteraction: "Never",
    source: "Public discovery",
  },
  {
    id: "h5",
    name: "Saurabh Gupta",
    initials: "SG",
    house: "HFS Research",
    houseTier: "Tier 2",
    role: "Research President & EVP",
    rating: "A",
    confidence: 0.83,
    stance: "Unknown",
    stanceConfidence: 0.37,
    coverage: ["Enterprise Services", "Cloud & Platform Services", "AI Strategy", "Digital Services"],
    lastInteraction: "Never",
    source: "Public discovery",
  },

  // ── NELSONHALL (Tier 2) ───────────────────────────────────────────────
  {
    id: "n1",
    name: "John Willmott",
    initials: "JW",
    house: "NelsonHall",
    houseTier: "Tier 2",
    role: "CEO & Principal Analyst",
    rating: "A+",
    confidence: 0.93,
    stance: "Unknown",
    stanceConfidence: 0.40,
    coverage: ["BPO", "IT Outsourcing", "Sourcing Advisory", "Digital Services"],
    lastInteraction: "Never",
    source: "Public discovery",
  },
  {
    id: "n2",
    name: "Gary Bragar",
    initials: "GB",
    house: "NelsonHall",
    houseTier: "Tier 2",
    role: "Research Director, HR Outsourcing",
    rating: "A+",
    confidence: 0.92,
    stance: "Unknown",
    stanceConfidence: 0.40,
    coverage: ["HR BPO", "Payroll Services", "Recruitment Process Outsourcing", "Learning BPO"],
    lastInteraction: "Never",
    source: "Public discovery",
  },
  {
    id: "n3",
    name: "Dominique Raviart",
    initials: "DR",
    house: "NelsonHall",
    houseTier: "Tier 2",
    role: "Principal Analyst, Intelligent Automation & AI",
    rating: "A+",
    confidence: 0.91,
    stance: "Unknown",
    stanceConfidence: 0.40,
    coverage: ["Intelligent Automation", "RPA", "AI Services", "Process Transformation"],
    lastInteraction: "Never",
    source: "Public discovery",
  },
  {
    id: "n4",
    name: "Tom Bangemann",
    initials: "TB",
    house: "NelsonHall",
    houseTier: "Tier 2",
    role: "VP Research, Finance & Accounting Transformation",
    rating: "A",
    confidence: 0.87,
    stance: "Unknown",
    stanceConfidence: 0.38,
    coverage: ["Finance & Accounting BPO", "Shared Services", "ERP Services", "GBS"],
    lastInteraction: "Never",
    source: "Public discovery",
  },
  {
    id: "n5",
    name: "Andy Efstathiou",
    initials: "AE",
    house: "NelsonHall",
    houseTier: "Tier 2",
    role: "Principal Research Analyst, Banking BPS",
    rating: "A",
    confidence: 0.85,
    stance: "Unknown",
    stanceConfidence: 0.38,
    coverage: ["Banking BPS", "Mortgage Processing", "Capital Markets BPO", "Financial Crime Ops"],
    lastInteraction: "Never",
    source: "Public discovery",
  },
  {
    id: "n6",
    name: "Ivan Kotzev",
    initials: "IK",
    house: "NelsonHall",
    houseTier: "Tier 2",
    role: "Research Analyst, Intelligent Automation",
    rating: "A",
    confidence: 0.83,
    stance: "Unknown",
    stanceConfidence: 0.37,
    coverage: ["RPA", "Intelligent Automation", "Contact Centre Automation", "AI Operations"],
    lastInteraction: "Never",
    source: "Public discovery",
  },
  {
    id: "n7",
    name: "Mike Smart",
    initials: "MS",
    house: "NelsonHall",
    houseTier: "Tier 2",
    role: "Research Director, BPO & Customer Experience",
    rating: "A",
    confidence: 0.82,
    stance: "Unknown",
    stanceConfidence: 0.37,
    coverage: ["BPO", "Customer Experience Services", "Contact Centre BPO", "CX Transformation"],
    lastInteraction: "Never",
    source: "Public discovery",
  },

  // ── ISG (Tier 2) ──────────────────────────────────────────────────────
  {
    id: "is1",
    name: "Jan Erik Aase",
    initials: "JA",
    house: "ISG",
    houseTier: "Tier 2",
    role: "Partner & Principal Analyst, Contact Center Services",
    rating: "A+",
    confidence: 0.89,
    stance: "Unknown",
    stanceConfidence: 0.39,
    coverage: ["Contact Centre Services", "CX Outsourcing", "CCaaS", "Customer Experience"],
    lastInteraction: "Never",
    source: "Public discovery",
  },
  {
    id: "is2",
    name: "Katy Ring",
    initials: "KR",
    house: "ISG",
    houseTier: "Tier 2",
    role: "Research Director, IT Services & Cloud",
    rating: "A",
    confidence: 0.85,
    stance: "Unknown",
    stanceConfidence: 0.37,
    coverage: ["IT Services", "Cloud Services", "Managed Services", "ITO"],
    lastInteraction: "Never",
    source: "Public discovery",
  },
  {
    id: "is3",
    name: "Esteban Herrera",
    initials: "EH",
    house: "ISG",
    houseTier: "Tier 2",
    role: "Partner, Contact Center & CX Outsourcing",
    rating: "A",
    confidence: 0.83,
    stance: "Unknown",
    stanceConfidence: 0.37,
    coverage: ["Contact Center BPO", "CX Analytics", "Automation in CX", "Workforce Management"],
    lastInteraction: "Never",
    source: "Public discovery",
  },
  {
    id: "is4",
    name: "Scott Feuless",
    initials: "SF",
    house: "ISG",
    houseTier: "Tier 2",
    role: "Partner, Outsourcing Advisory",
    rating: "A",
    confidence: 0.82,
    stance: "Unknown",
    stanceConfidence: 0.37,
    coverage: ["Outsourcing Advisory", "Sourcing Strategy", "Contract Negotiations", "Managed Services"],
    lastInteraction: "Never",
    source: "Public discovery",
  },
  {
    id: "is5",
    name: "Debi Walker",
    initials: "DW",
    house: "ISG",
    houseTier: "Tier 2",
    role: "Research Director, Automation & AI",
    rating: "A",
    confidence: 0.81,
    stance: "Unknown",
    stanceConfidence: 0.36,
    coverage: ["RPA", "Intelligent Automation", "AI Services", "Process Automation"],
    lastInteraction: "Never",
    source: "Public discovery",
  },
  {
    id: "is6",
    name: "Stacey Cadigan",
    initials: "SC",
    house: "ISG",
    houseTier: "Tier 2",
    role: "Partner, HR Technology & Outsourcing",
    rating: "B+",
    confidence: 0.77,
    stance: "Unknown",
    stanceConfidence: 0.34,
    coverage: ["HR Outsourcing", "HR Technology", "Payroll BPO", "Talent Acquisition Services"],
    lastInteraction: "Never",
    source: "Public discovery",
  },
  {
    id: "is7",
    name: "Mark Davey",
    initials: "MD",
    house: "ISG",
    houseTier: "Tier 2",
    role: "Partner, Sourcing Strategy & Governance",
    rating: "B+",
    confidence: 0.75,
    stance: "Unknown",
    stanceConfidence: 0.34,
    coverage: ["Sourcing Governance", "Multi-Sourcing", "Contract Management", "Supplier Management"],
    lastInteraction: "Never",
    source: "Public discovery",
  },
];

export type Workstream = {
  id: string;
  title: string;
  house: string;
  model: string;
  owner: string;
  due: string;
  progress: number; // 0..100
  status: "On track" | "At risk" | "Blocked" | "Submitted";
  readiness: ReadinessBand;
  analystIds: string[];
};

export const WORKSTREAMS: Workstream[] = [
  {
    id: "w1",
    title: "Gartner MQ — Application Modernisation 2026",
    house: "Gartner",
    model: "Magic Quadrant",
    owner: "Mireille Okonkwo",
    due: "12 Jun",
    progress: 62,
    status: "On track",
    readiness: "Adequate",
    analystIds: ["g3", "g9"],
  },
  {
    id: "w2",
    title: "Forrester Wave — Modern Application Development Services",
    house: "Forrester",
    model: "Wave",
    owner: "Dev Patel",
    due: "28 May",
    progress: 41,
    status: "At risk",
    readiness: "Weak",
    analystIds: ["f1", "f2"],
  },
  {
    id: "w3",
    title: "Everest PEAK Matrix — BFSI IT Services",
    house: "Everest Group",
    model: "PEAK Matrix",
    owner: "Ana Reis",
    due: "19 Jun",
    progress: 78,
    status: "On track",
    readiness: "Strong",
    analystIds: ["e4", "e5"],
  },
  {
    id: "w4",
    title: "HFS Horizons — Generative Enterprise Services",
    house: "HFS Research",
    model: "Horizons",
    owner: "Mireille Okonkwo",
    due: "05 Jul",
    progress: 24,
    status: "Blocked",
    readiness: "Missing",
    analystIds: ["h1", "h2"],
  },
  {
    id: "w5",
    title: "IDC MarketScape — AI Services Worldwide",
    house: "IDC",
    model: "MarketScape",
    owner: "Hideo Tanaka",
    due: "30 May",
    progress: 88,
    status: "Submitted",
    readiness: "Strong",
    analystIds: ["i1", "i3"],
  },
];

export type SuggestedTask = {
  id: string;
  title: string;
  workstreamId: string;
  due: string;
  basis: string;
  confidence: number;
  source: string;
};

export const SUGGESTED_TASKS: SuggestedTask[] = [
  {
    id: "t1",
    title: "Schedule 30-min briefing with Helen Huntley on App Modernisation case studies",
    workstreamId: "w1",
    due: "in 4 days",
    basis: "RFI section 3.2 references 2 anonymised clients — Gartner historically requires 5+ named references for Leader placement.",
    confidence: 0.81,
    source: "Gartner MQ — App Modernisation RFI draft v3",
  },
  {
    id: "t2",
    title: "Source proof point on BFSI AI Co-pilot deployment for Forrester Wave",
    workstreamId: "w2",
    due: "in 9 days",
    basis: "Wave criterion 'AI-assisted dev tooling' is currently Unsupported. Sales pipeline shows 2 active BFSI AI Co-pilot deals.",
    confidence: 0.73,
    source: "Forrester Wave criteria checklist",
  },
  {
    id: "t3",
    title: "Confirm OneEcosystem narrative for HFS Horizons RFI",
    workstreamId: "w4",
    due: "in 2 days",
    basis: "Draft RFI section on partner ecosystem mentions 2 hyperscaler partners only. HFS OneEcosystem framework expects multi-tier ecosystem narrative.",
    confidence: 0.86,
    source: "HFS Horizons RFI draft v1",
  },
  {
    id: "t4",
    title: "Capture interaction record for Akhilesh Tumar briefing on 06 May",
    workstreamId: "w3",
    due: "overdue 1 day",
    basis: "Calendar event 'Northstar / Everest BFSI deep-dive' marked complete; no interaction record logged.",
    confidence: 0.92,
    source: "Calendar sync",
  },
];

export type EvidenceItem = {
  id: string;
  title: string;
  type: "Case study" | "Metric" | "Client reference" | "Capability proof" | "Outcome";
  workstreamId: string;
  readiness: ReadinessBand;
  reuse: string;
  status: "Suggested" | "Approved" | "Approved with restrictions" | "Rejected";
  provenance: string;
  confidence: number;
};

export const EVIDENCE: EvidenceItem[] = [
  {
    id: "e1",
    title: "BFSI Core Modernisation — 38% TCO reduction over 24 months",
    type: "Outcome",
    workstreamId: "w1",
    readiness: "Strong",
    reuse: "Analyst briefing approved under NDA",
    status: "Approved",
    provenance: "Q3 2025 case study, Marketing approved, customer-named",
    confidence: 0.91,
  },
  {
    id: "e2",
    title: "Retail AI Co-pilot pilot — 11% release velocity uplift",
    type: "Metric",
    workstreamId: "w2",
    readiness: "Adequate",
    reuse: "Internal only",
    status: "Suggested",
    provenance: "Extracted from SharePoint: Retail Practice QBR Q1 2026",
    confidence: 0.72,
  },
  {
    id: "e3",
    title: "Insurer claims automation — 4 weeks to production",
    type: "Case study",
    workstreamId: "w3",
    readiness: "Strong",
    reuse: "RFI approved",
    status: "Approved",
    provenance: "Approved RFI library, last refreshed 18 Apr 2026",
    confidence: 0.89,
  },
  {
    id: "e4",
    title: "OneEcosystem partner narrative — proposed",
    type: "Capability proof",
    workstreamId: "w4",
    readiness: "Weak",
    reuse: "Internal only",
    status: "Suggested",
    provenance: "Drafted by AR Superhero from public partner page + 3 internal QBRs",
    confidence: 0.61,
  },
  {
    id: "e5",
    title: "Generative AI delivery factory — headcount + cities",
    type: "Capability proof",
    workstreamId: "w5",
    readiness: "Adequate",
    reuse: "Analyst briefing approved no NDA required",
    status: "Approved with restrictions",
    provenance: "HR system sync — restricted to country-level numbers only",
    confidence: 0.79,
  },
];

export type IntelSignal = {
  id: string;
  title: string;
  source: string;
  when: string;
  type: "Public" | "Internal sync" | "AR platform" | "Email";
  workstreamId?: string;
  summary: string;
  needsConfirmation?: boolean;
};

export const SIGNALS: IntelSignal[] = [
  {
    id: "s1",
    title: "Gartner research note published: 'How to Win in App Modernisation 2026'",
    source: "Gartner.com",
    when: "2 hours ago",
    type: "Public",
    workstreamId: "w1",
    summary:
      "Note emphasises composable architectures and named refactor playbooks. Mentions 3 competitors; Northstar Digital not referenced.",
  },
  {
    id: "s2",
    title: "Phil Fersht (HFS) — LinkedIn post on OneEcosystem maturity",
    source: "LinkedIn (public)",
    when: "5 hours ago",
    type: "Public",
    workstreamId: "w4",
    summary:
      "Argues that 70%+ of vendors underweight internal-business-unit collaboration; calls for tighter partner + internal ecosystem motion.",
  },
  {
    id: "s3",
    title: "Briefing held: Akhilesh Tumar / Everest — BFSI IT Services deep dive",
    source: "Calendar + Spotlight Analyst Portals",
    when: "Yesterday",
    type: "AR platform",
    workstreamId: "w3",
    summary:
      "Candidate interaction record auto-created from calendar + Spotlight. Three follow-ups proposed.",
    needsConfirmation: true,
  },
  {
    id: "s4",
    title: "Inbound email: Helen Huntley — RFI clarification",
    source: "AR shared mailbox",
    when: "Yesterday",
    type: "Email",
    workstreamId: "w1",
    summary:
      "Requests 2 additional named references in EMEA Banking. Suggested task created.",
  },
  {
    id: "s5",
    title: "ARchitect: Forrester Wave inclusion confirmed",
    source: "ARchitect / ARInsights",
    when: "3 days ago",
    type: "AR platform",
    workstreamId: "w2",
    summary: "Status field synced from ARchitect. Workstream auto-linked.",
  },
];

export type LearningItem = {
  id: string;
  signal: string;
  state:
    | "Raw signal"
    | "Candidate pattern"
    | "Watchlist"
    | "Validated pattern"
    | "Deprecated pattern"
    | "Rejected signal";
  scope: string;
  anonymised: boolean;
  reviewer: string;
};

export const LEARNING: LearningItem[] = [
  {
    id: "l1",
    signal:
      "HFS RFIs scoring 'Strong' more often when partner narrative covers 3+ ecosystem tiers (hyperscaler, ISV, regional)",
    state: "Candidate pattern",
    scope: "HFS Horizons — all vendors",
    anonymised: true,
    reviewer: "Awaiting AnalystGenius head researcher",
  },
  {
    id: "l2",
    signal:
      "Gartner MQ App Modernisation: named references in 3+ regions correlated with movement towards Leader quadrant",
    state: "Validated pattern",
    scope: "Gartner MQ — App Modernisation",
    anonymised: true,
    reviewer: "Cross-checked by AnalystGenius",
  },
  {
    id: "l3",
    signal:
      "Forrester Wave: vendors who decline strategy demo lose 1-2 criteria score points on average",
    state: "Watchlist",
    scope: "Forrester Wave — services categories",
    anonymised: true,
    reviewer: "AnalystGenius monitoring",
  },
  {
    id: "l4",
    signal:
      "Everest PEAK BFSI: AI-assisted operations evidence weighs heavier in 2026 cycle",
    state: "Raw signal",
    scope: "Everest PEAK BFSI",
    anonymised: true,
    reviewer: "Not yet reviewed",
  },
];

export type Integration = {
  id: string;
  name: string;
  category:
    | "Public intelligence"
    | "AR platform"
    | "Document store"
    | "Email & calendar";
  mode: "Read-only" | "Continuous sync" | "Off";
  scope: string;
  lastSync: string;
  enabled: boolean;
};

export const INTEGRATIONS: Integration[] = [
  { id: "i1", name: "Gartner.com public", category: "Public intelligence", mode: "Continuous sync", scope: "Watched analysts + Magic Quadrants", lastSync: "12m ago", enabled: true },
  { id: "i2", name: "Forrester.com public", category: "Public intelligence", mode: "Continuous sync", scope: "Watched analysts + Wave categories", lastSync: "18m ago", enabled: true },
  { id: "i3", name: "HFS Research public", category: "Public intelligence", mode: "Continuous sync", scope: "OneOffice + Horizons", lastSync: "1h ago", enabled: true },
  { id: "i4", name: "LinkedIn public posts", category: "Public intelligence", mode: "Continuous sync", scope: "Watched analyst list", lastSync: "23m ago", enabled: true },

  { id: "i5", name: "ARchitect / ARInsights", category: "AR platform", mode: "Read-only", scope: "All workstreams, interactions", lastSync: "42m ago", enabled: true },
  { id: "i6", name: "AR Connect", category: "AR platform", mode: "Read-only", scope: "Briefing requests", lastSync: "1h ago", enabled: true },
  { id: "i7", name: "Spotlight Oz", category: "AR platform", mode: "Read-only", scope: "ANZ analysts", lastSync: "2h ago", enabled: false },
  { id: "i8", name: "Spotlight Analyst Portals", category: "AR platform", mode: "Continuous sync", scope: "Active assessments", lastSync: "37m ago", enabled: true },

  { id: "i9", name: "SharePoint — AR Workspace", category: "Document store", mode: "Read-only", scope: "/AR Submissions, /Case Studies", lastSync: "5m ago", enabled: true },
  { id: "i10", name: "OneDrive", category: "Document store", mode: "Read-only", scope: "AR team folder", lastSync: "11m ago", enabled: true },
  { id: "i11", name: "Google Drive", category: "Document store", mode: "Off", scope: "—", lastSync: "—", enabled: false },
  { id: "i12", name: "Box", category: "Document store", mode: "Off", scope: "—", lastSync: "—", enabled: false },
  { id: "i13", name: "Dropbox", category: "Document store", mode: "Off", scope: "—", lastSync: "—", enabled: false },

  { id: "i14", name: "AR shared mailbox", category: "Email & calendar", mode: "Continuous sync", scope: "ar@northstar.example", lastSync: "4m ago", enabled: true },
  { id: "i15", name: "AR team calendars", category: "Email & calendar", mode: "Continuous sync", scope: "5 calendars", lastSync: "4m ago", enabled: true },
];

export const STANCE_OPTIONS: Stance[] = [
  "Friendly",
  "Neutral",
  "Inattentive",
  "Irrelevant",
  "Combative",
  "Unknown",
];

export const READINESS_BANDS: ReadinessBand[] = [
  "Strong",
  "Adequate",
  "Weak",
  "Missing",
  "Unsupported",
];

export const LENSES = [
  {
    id: "strategy",
    name: "Strategy",
    summary:
      "Northstar's analyst-visible strategy must over-index on App Modernisation and BFSI AI Operations. Two flagship assessments (Gartner MQ, Everest PEAK BFSI) align with stated FY26 priorities; HFS Horizons is the outlier requiring a sharper ecosystem narrative.",
    points: [
      "Sequence Gartner MQ as anchor narrative — leader-band positioning supports 3 downstream RFIs.",
      "Re-state BFSI AI Operations point of view in time for Forrester Wave and IDC MarketScape (overlap window: 4 weeks).",
      "Decide whether to pursue HFS Horizons in this cycle or defer; current readiness is Weak/Missing on OneEcosystem narrative.",
    ],
  },
  {
    id: "executive",
    name: "Executive",
    summary:
      "Three of five active assessments are on or ahead of plan. One (Forrester Wave) is At risk; one (HFS Horizons) is Blocked. Recommend a 20-minute exec review focused on Wave evidence gaps and HFS go/no-go.",
    points: [
      "Pipeline: 5 active assessments, 1 submitted, 0 declined.",
      "Risk: 2 assessments dependent on the same 2 BFSI references — concentration risk.",
      "Investment ask: 1 strategy session with AnalystGenius on HFS Horizons before next sprint.",
    ],
  },
  {
    id: "product",
    name: "Product",
    summary:
      "Capability and evidence gaps cluster around AI-assisted developer tooling and partner-led delivery. No roadmap recommendations are made here — gaps below should be reviewed with Product leadership and AnalystGenius analysts.",
    points: [
      "Capability gap: AI-assisted developer co-pilot — proof points exist as pilots only.",
      "Evidence gap: Multi-tier partner delivery — minimal documented client outcomes.",
      "Suggested next step: schedule a strategy session with AnalystGenius on Horizons readiness.",
    ],
  },
  {
    id: "marketing",
    name: "Marketing",
    summary:
      "Internal marketing guidance only. Storylines that resonate in current analyst inquiries should be reflected in internal sales-enablement and analyst briefing materials — not in external campaigns.",
    points: [
      "Sharpen internal narrative on App Modernisation — Gartner inquiries trending up 22% QoQ.",
      "Reposition BFSI AI co-pilot collateral for analyst briefings; existing pieces are too sales-led.",
      "Do not externalise analyst quotes without explicit approval (NDA controls apply).",
    ],
  },
  {
    id: "commercial",
    name: "Commercial",
    summary:
      "Analyst influence enablement for internal sales leaders. Focus is on shaping how analyst positioning is used inside the sales motion, not on deal-room intelligence or competitor deal dynamics.",
    points: [
      "Equip BFSI sales leaders with 2-pager on Northstar's analyst visibility (Gartner, Everest, IDC).",
      "Brief North America Banking pursuit team ahead of 2 named pursuits; reference 3 approved evidence items.",
      "Flag: Restrict use of NDA-only analyst quotes in commercial conversations.",
    ],
  },
];
