// Vercel serverless entry for the AR Superhero API.
//
// dist/server/app.cjs is generated by `npm run build` (script/build.ts): a
// self-contained CJS bundle of the Express app with the @shared path alias
// resolved and all real packages kept external (resolved by Vercel's tracer).
// This file only does a relative re-export, so no build-time path alias ever
// reaches the Node runtime. Vercel invokes the exported Express app per request.
//
// @ts-ignore — generated build artifact, no type declarations
import mod from "../dist/server/app.cjs";

const app = (mod as any)?.default ?? mod;
export default app;
